### ISSUE TITLE
KeyError: 'Bacteria'

### ISSUE THREAD

**Issue by chassenr** [KIT-IBG-5/mdmcleaner#38]
Hi, 

I have been running MDMcleaner on 2 different bin sets. In one run, not all bins were processed without error (see #37). Using the same reference data, I am now getting the following error for the last bin to be processed:

```
--> writing to output files
        writing detailed contig infos to ./T4-48_bin.49.orig/fullcontiginfos_beforecleanup.tsv
        appending overview data to overview_all_before_cleanup.tsv
        creating output fastas
        creating krona input-table
reference-database contaminations detected during this run: 69
blasting 13 entries with blastx against reference proteins (another 5 entries were too long to blastx efficiently
Traceback (most recent call last):
  File "/bio/Software/anaconda3/envs/mdmcleaner-0.8.3/bin/mdmcleaner", line 10, in <module>
    sys.exit(main())
  File "/bio/Software/anaconda3/envs/mdmcleaner-0.8.3/lib/python3.10/site-packages/mdmcleaner/mdmcleaner.py", line 217, in main
    blacklist_additions = clean.main(args, configs)
  File "/bio/Software/anaconda3/envs/mdmcleaner-0.8.3/lib/python3.10/site-packages/mdmcleaner/clean.py", line 230, in main
    if "contamination" in db_suspects.collective_diamondblast():
  File "/bio/Software/anaconda3/envs/mdmcleaner-0.8.3/lib/python3.10/site-packages/mdmcleaner/review_refdbcontams.py", line 319, in collective_diamondblast
    eval_list.append(self.evaluateornot(self.blastxjobs[x], blastxdone = True))
  File "/bio/Software/anaconda3/envs/mdmcleaner-0.8.3/lib/python3.10/site-packages/mdmcleaner/review_refdbcontams.py", line 283, in evaluateornot
    return_category, return_note = comp.count_contradictions() #todo: redundant. streamline blastcontigs() and countcontradictions() more
  File "/bio/Software/anaconda3/envs/mdmcleaner-0.8.3/lib/python3.10/site-packages/mdmcleaner/review_refdbcontams.py", line 123, in count_contradictions
    domain_counts_expected = domain_counts[comparison_domain] #todo: only in try_except statement for debugging
KeyError: 'Bacteria'
```

Any advice would be appreciated. Thanks!

**Comment by jvollme** [comment]
I will look into this error. Would be great if you could send me the problematic bin fastas fort that if possible, though.

Until then a temporary workaround may be to use the --fast_run argument here als, as already suggested for #37 (preferrably only for the problematic bins though).

**Comment by chassenr** [comment]
I re-ran MDMcleaner for this bin set omitting the bin that seemed to have caused the error in the previous run. However, I received the same error message for the last bin to be run. Maybe the error message is related to a step in the program that is run after the individual processing of the bins? The bin_name_filtered_*.gz files are written for all bins and the error list file is empty. However, despite the potential reference DB contamination that was detected during the run (according the log file) no new_blacklist_additions.tsv is being produced. I am now re-running the complete bin set with the --fast_run option. That worked without a problem. I find it curious, though, that I only received the ```KeyError: 'Bacteria'``` when running MDMcleaner for this bin set, and not the one that I refer to in #37. I used the same database and conda environment.

**Comment by jvollme** [comment]
for some reeason i could not reproduce this particular error for the test bins provided. But i added a temporary fix for the related "silva_conflict" problem. please Contact me if this keyerror still persists with the new mdmcleaner version and database...

**Comment by chassenr** [comment]
Hi @jvollme ,

I am very sorry that it took me so long to get back to you. I updated MDMcleaner to the latest version and all my previous issues were resolved. Thank you so much. Everything seems to have worked fine. However, I get the following error message at the end of the run:

```

------------------------------finished------------------------------
Traceback (most recent call last):
  File "/bio/Software/anaconda3/envs/mdmcleaner-0.8.7/bin/mdmcleaner", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/bio/Software/anaconda3/envs/mdmcleaner-0.8.7/lib/python3.11/site-packages/mdmcleaner/mdmcleaner.py", line 214, in main
    blacklist_additions = clean.main(args, configs)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/bio/Software/anaconda3/envs/mdmcleaner-0.8.7/lib/python3.11/site-packages/mdmcleaner/clean.py", line 243, in main
    os.remove(f)
FileNotFoundError: [Errno 2] No such file or directory: './tempdir_dnlaipkf_mdmcleaner_refdbcontam/refblast_GCA_001443455.1_LDXO01000018.1__000blastn_auxblasts_vs_concat_refgenomes.tsv'
```

I assume that this is just related to post-run cleaning steps and not affecting the results for the individual bins?

Thanks!

Cheers,
Christiane

**Comment by taorong007** [comment]
Hi @jvollme,

We encountered the same `KeyError: 'Bacteria'` with **MDMcleaner 0.8.7** during the final reference-database review. We are using MDMcleaner as a baseline in a MAG refinement benchmark and would appreciate advice on resolving this while retaining the full workflow.

### Environment

- Python: 3.14.7
- Biopython: 1.88
- NumPy: 2.5.2
- BLAST: 2.17.0
- DIAMOND: 2.2.5
- HMMER: 3.4
- Prodigal: 2.6.3
- barrnap: 0.9
- ARAGORN: 1.2.41
- Reference database version records: GTDB R95, RefSeq release203, SILVA 138.1

### Input and command

The input consists of 264 CONCOCT bins from a freshwater sample (`ERR9631077`). The command below is equivalent to the logged invocation, with local paths abbreviated; the original invocation explicitly listed all 264 FASTA files.

```bash
mdmcleaner clean \
    -i /path/to/input_bins/*.fa \
    -o /path/to/work \
    -c /path/to/mdmcleaner.config \
    -t 32 \
    --overview_files_basename /path/to/work/overview
```

The configuration specifies `db_type gtdb` and the database directory. The log confirms that the effective thread count was 32. We did not use `--fast_run`.

### Observed failure

Filtered FASTA files and per-contig reports were generated for all 264 bins, and `overview_errorlist.txt` is empty. The command then exited with the following error (paths abbreviated):

```text
reference-database contaminations detected during this run: 29
blasting 42 entries with blastx against reference proteins (another 39 entries were too long to blastx efficiently
Traceback (most recent call last):
  File ".../mdmcleaner/mdmcleaner.py", line 214, in main
    blacklist_additions = clean.main(args, configs)
  File ".../mdmcleaner/clean.py", line 230, in main
    if "contamination" in db_suspects.collective_diamondblast():
  File ".../mdmcleaner/review_refdbcontams.py", line 319, in collective_diamondblast
    eval_list.append(self.evaluateornot(self.blastxjobs[x], blastxdone = True))
  File ".../mdmcleaner/review_refdbcontams.py", line 283, in evaluateornot
    return_category, return_note = comp.count_contradictions()
  File ".../mdmcleaner/review_refdbcontams.py", line 123, in count_contradictions
    domain_counts_expected = domain_counts[comparison_domain]
KeyError: 'Bacteria'
```

### Additional diagnostic evidence

In the retained collective DIAMOND blastx output, reference accession `GCA_002401495.1_NVTG01000112.1` has 25 hits with identities of 34.7–40.1%. Applying the existing parsing settings in `collective_diamondblast` (`min_ident=90`, `max_evalue=1e-5`) leaves zero hits for this accession.

The attached ZIP contains a small reproduction script and the 25 original blastx hit rows. In an environment with MDMcleaner 0.8.7 installed, extract the archive and run `python reproduce.py`. No reference database or new alignments are needed. With the expected domain set to `Bacteria`, the empty hit set triggers `KeyError: 'Bacteria'` in the unmodified MDMcleaner function. This reproduces the empty-hit failure path; the original log does not identify which accession triggered the crash.

### Questions

1. We are using the publication R95 database, and the existing runs have already taken several days. **Is there a way to resolve this error while retaining that database?** We would prefer to avoid restarting the entire analysis with a different database if possible.

2. What is the intended handling when no hits survive filtering during reference-database review? We saw your earlier recommendation to use `--fast_run` as a workaround, but would prefer to retain the full workflow for our primary comparison. Is there a supported way to complete this review without disabling it?

3. Does failure at this stage affect the validity of the already-written filtered bins, and how should we resume from the retained intermediate files to complete the workflow correctly? We have preserved those outputs, but are not treating their presence alone as evidence that the full workflow completed successfully.

Attached: `mdmcleaner_issue38_reproduction.zip`, containing the reproduction script, required hit data, original log excerpts with local paths abbreviated, environment versions and a README. We have preserved the full original logs and intermediate files if further information is needed.

Thank you!

[mdmcleaner_issue38_reproduction.zip](https://github.com/user-attachments/files/31954893/mdmcleaner_issue38_reproduction.zip)
